ci:
  autoupdate_schedule: quarterly

default_install_hook_types: [pre-commit, commit-msg]

exclude: pnpm-lock.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: ^assets/.+\.svg$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        stages: [commit]
        args: [--write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        exclude_types: [svg]
        args: [--ignore-words-list, "noe,ket,ba,te,nd"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        # MD013: line too long
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        args: [--disable, MD013, MD033, MD041, "--"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.31.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(svelte|js|ts)$
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte3
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
